---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: Cloud Data Sense の新機能をご確認ください。 
---
= Cloud Data Sense の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Data Sense の新機能をご確認ください。



== 2022年7月6日（バージョン1.14）



=== これで、ディレクトリにアクセスできるユーザとグループを表示できます

これまでは、個々のファイルに付与されているオープンアクセス権のタイプを表示できました。これで、ディレクトリ（フォルダおよびファイル共有）にアクセスできるすべてのユーザまたはグループ、およびディレクトリにアクセスできる権限のタイプのリストが表示されます。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["フォルダおよびファイル共有にアクセスできるユーザとグループを表示する方法について説明します"]。



=== リポジトリのスキャンを一時停止すると'特定のコンテンツのスキャンを一時的に停止できます

スキャンを一時停止すると、ボリュームやバケットへの追加や変更はデータスキャンを実行できなくなりますが、現在の結果はすべてシステムで使用できるようになります。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["スキャンを一時停止および再開する方法を参照してください"]。



=== 3つの追加状態からのUSドライバーのライセンスデータは、データセンスで識別できます

データセンスは、インディアナ、ニューヨーク、テキサスの運転免許証データを含むファイルを識別して分類できます。 link:reference-private-data-categories.html#types-of-personal-data["データで特定できるすべての種類の個人データを表示します"]。



=== ポリシーは、検索条件に一致するディレクトリを返すようになりました

以前は、カスタムポリシーを作成したときに、検索条件に一致したファイルが結果に表示されていました。これで、クエリに一致するディレクトリ（フォルダおよびファイル共有）も結果に表示されます。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies["ポリシーの作成の詳細については、こちらをご覧ください"]。



=== データセンスでは、一度に最大100,000個のファイルを移動できます

スキャンしたデータソースからNFS共有へのファイル移動にData Senseを使用する場合は、ファイルの最大数が100、000ファイルに増加しています。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["データセンスを使用してファイルを移動する方法をご覧ください"]。



== 2022年6月12日（バージョン1.13.1）



=== Data Investigationページから結果を.jsonレポートとしてダウンロードできるようになりました

[データ調査]ページでデータをフィルタリングした後、データを.jsonファイルに保存してNFS共有にエクスポートできます。これにより、ローカルシステム上の.csvファイルにデータを保存することができます。データセンスにエクスポートアクセスのための正しい権限があることを確認します。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report["Data Investigationページからレポートを作成する方法を参照してください"]。



=== データセンスUIからデータセンスをアンインストールする機能

Data Senseをアンインストールして、ソフトウェアをホストから完全に削除することができます。クラウドの導入の場合は、Data Senseが導入されていた仮想マシン/インスタンスを削除します。インスタンスを削除すると、データセンスがスキャンしたインデックス情報がすべて完全に削除されます。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html["方法を参照してください"]。



=== 監査ログを使用して、データ検出によって実行されたアクションの履歴を追跡できるようになりました

監査ログは、データがスキャンしているすべての作業環境およびデータソースから、ファイルに対してデータが実行した管理アクティビティを追跡します。アクティビティには、ユーザが生成するアクティビティ（ファイルの削除、ポリシーの作成など）と生成されるポリシー（ファイルにラベルを自動的に追加するアクティビティ、ファイルを自動的に削除するアクティビティなど）があります。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html["監査ログの詳細を確認してください"]。



=== [データ調査]ページの重要な識別子の数に対する新しいフィルタ

「Number of identifiers（識別子の数）」フィルタを使用すると、個人データと機密性の高い個人データの両方を含む、一定数の機密識別子を持つファイルをリストできます。1-10や501-1000などの範囲を選択すると、その数の機密識別子を含むファイルのみを表示できます。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["データの調査に使用できるすべてのフィルタのリストを確認します"]。



=== これで、作成した既存のポリシーを編集できるようになります

以前に作成したカスタムポリシーに変更を加える必要がある場合は、新しいポリシーを作成する代わりにポリシーを編集できるようになりました。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies["ポリシーの編集方法については、を参照してください"]。



== 2022年5月11日（バージョン1.12.1）



=== Google Driveアカウントでのデータスキャンのサポートが追加されました

Googleドライブアカウントからドキュメントやファイルをスキャンするために、Googleドライブアカウントをデータセンスに追加できるようになりました。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html["Googleドライブアカウントをスキャンする方法をご覧ください"]。

データセンスは、に加えて、Googleドキュメントスイート（ドキュメント、シート、スライド）からGoogleファイルタイプ内の個人識別情報（PII）を識別できます https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files["既存のファイルタイプ"]。



=== [データ調査]ページに追加されたディレクトリレベルビュー

すべてのファイルおよびデータベースのデータを表示およびフィルタリングするだけでなく、[データ調査]ページのフォルダおよび共有内のすべてのデータに基づいてデータを表示およびフィルタリングできるようになりました。ディレクトリには、スキャンされたCIFS共有とNFS共有、OneDrive、SharePoint、Google Driveフォルダのインデックスが作成されます。これで、権限を表示し、ディレクトリレベルでデータを管理できるようになりました。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["スキャンしたデータのディレクトリビューを選択する方法を参照してください"]。



=== グループを展開して、ファイルにアクセスする権限を持つユーザー/メンバーを表示します

データセンス権限機能の一部として、ファイルにアクセスできるユーザとグループのリストを表示できるようになりました。各グループを展開すると、グループ内のユーザのリストが表示されます。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files["ファイルに対する読み取り権限または書き込み権限を持つユーザーおよびグループを表示する方法を参照してください"]。



=== 2つの新しいフィルタが[データ調査]ページに追加されました

* 「ディレクトリタイプ」フィルタを使用すると、フォルダまたは共有のみを表示するようにデータを絞り込むことができます。結果は新しい*ディレクトリ*タブに表示されます。
* 「ユーザ/グループの権限」フィルタを使用すると、特定のユーザまたはグループに対する読み取り/書き込み権限があるファイル、フォルダ、および共有を表示できます。複数のユーザまたはグループの名前を選択するか、名前の一部を入力できます。t


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["データの調査に使用できるすべてのフィルタのリストを確認します"]。



== 2022年4月5日（バージョン1.11.1）



=== オーストラリアの個人データは、データセンスで新たに 4 種類識別できます

データセンスでは、オーストラリア TFN ( 税ファイル番号 ) 、オーストラリア運転免許証番号、オーストラリア医薬品番号、オーストラリアパスポート番号を含むファイルを識別し、分類することができます。 link:reference-private-data-categories.html#types-of-personal-data["データで特定できるすべての種類の個人データを表示します"]。



=== グローバル Active Directory サーバを LDAP サーバとして使用できるようになりました

Data Sense と統合するグローバル Active Directory サーバは、以前にサポートされていた DNS サーバに加えて、 LDAP サーバにすることができます。 link:task-add-active-directory-datasense.html["詳細については、こちらをご覧ください"]。



== 2022年3月15日（バージョン1.10.0）



=== 新しいフィルタ：特定のユーザまたはグループに読み取りまたは書き込み権限があるファイルを表示します

「ユーザ / グループの権限」という新しいフィルタが追加され、特定のユーザまたはグループの読み取り / 書き込み権限を持つファイルを一覧表示できるようになりました。1つ以上のユーザ名またはグループ名を選択するか、または名前の一部を入力できます。この機能は、 Cloud Volumes ONTAP 、オンプレミス ONTAP 、 Azure NetApp Files 、 Amazon FSX for ONTAP 、およびファイル共有のボリュームで使用できます。



=== データセンスを使用すると、 SharePoint アカウントと OneDrive アカウントのファイルに対する権限を決定できます

データセンスでは、 OneDrive アカウントと SharePoint アカウントでスキャン中のファイルに存在するアクセス許可を読み取ることができます。この情報は、ファイルの [ 調査 ] ペインの詳細、およびガバナンスダッシュボードの [ アクセス許可を開く ] 領域に表示されます。



=== 追加の 2 種類の個人データは、データセンスで識別できます

* フランスの INSEE - INSEE コードは、フランス国立統計経済研究所（ INSEE ）がさまざまなエンティティを識別するために使用する数値コードです。
* パスワード - この情報は、英数字の文字列の横にある「 password 」という単語を検索して、近接性検証を使用して識別されます。見つかったアイテムの数は、コンプライアンスダッシュボードの [ 個人の結果 ] の下に表示されます。［ 調査 ］ ペインでパスワードを含むファイルを検索するには、 ［ フィルタ * 個人データ ］ > ［ パスワード * ］ を使用します。




=== ダークサイトに導入した場合、 OneDrive と SharePoint のデータをスキャンできます

インターネットにアクセスできないオンプレミスサイトのホストに Cloud Data Sense を導入した場合、 OneDrive アカウントまたは SharePoint アカウントからローカルデータをスキャンできるようになりました。 link:task-deploy-compliance-dark-site.html#sharepoint_and_onedrive_special_requirements["次のエンドポイントへのアクセスを許可する必要があります。"]



=== Cloud Data Sense を使用して Cloud Backup ファイルをスキャンするベータ機能は、本リリースでは廃止されました



== 2022 年 2 月 9 日



=== Microsoft SharePoint オンラインアカウントのスキャンのサポートが追加されました

SharePoint サイトからドキュメントやファイルをスキャンするために、 SharePoint オンラインアカウントをデータセンスに追加できるようになりました。 link:task-scanning-sharepoint.html["SharePoint アカウントをスキャンする方法をご覧ください"]。



=== データセンスでは、データソースからターゲットの場所にファイルをコピーし、それらのファイルを同期できます

これは、データを移行していて、ファイルに加えられた最後の変更を確認する場合に役立ちます。このアクションではを使用します https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["NetApp Cloud Sync の略"^] データをソースからターゲットにコピーおよび同期する機能。

link:task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["ファイルのコピーおよび同期方法を参照してください"]。



=== dsar レポートの新しい言語サポート

データ主体の名前を検索して Data Subject Access Request （ dsar ）レポートを作成するときに、ドイツ語とスペイン語がサポートされるようになりました。このレポートは、企業が GDPR または同様のデータプライバシー法を遵守する必要がある場合に役立つように作成されています。



=== 追加の 3 種類の個人データは、データセンスで識別できます

データセンスでは、ファイル内にフランス語のソーシャルセキュリティ番号、フランス語の ID 、フランス語のドライバーライセンス番号が表示されるようになりました。 link:reference-private-data-categories.html#types-of-personal-data["データがスキャンで識別するすべての個人データタイプのリストを表示します"]。



=== コネクタへのデータセンス通信のためにセキュリティグループポートが変更されました

Cloud Manager Connector のセキュリティグループでは、セキュリティを強化するために、データセンスインスタンスとの間のインバウンドトラフィックとアウトバウンドトラフィックにポート 80 ではなくポート 443 が使用されます。この時点では両方のポートは開いたままなので、問題はありませんが、将来のリリースではポート 80 が廃止される予定であるため、以前のどの環境でもセキュリティグループを更新する必要があります。



== 2022 年 1 月 2 日



=== グローバル Active Directory を統合して、ファイルの所有者と権限を識別する機能

グローバル Active Directory を Cloud Data Sense と統合することで、ファイル所有者や、ファイルにアクセスできるユーザーやグループについてデータセンスがレポートする結果を高めることができます。

Data Sense で特定のデータソースから CIFS ボリュームをスキャンできるように入力する Active Directory クレデンシャルに加えて、この新しい統合によって他のユーザやシステムも統合されるようになります。データセンスは、統合されたすべての Active Directory でユーザと権限の詳細を確認します。 link:task-add-active-directory-datasense.html["グローバル Active Directory の設定方法を参照してください"]。



=== データセンスの「ポリシー」を使用してファイルを削除できるようになりました

データセンスでは、ポリシーで定義したクエリに一致するファイルを自動的に削除できます。 link:task-managing-highlights.html#deleting-source-files-automatically-using-policies["カスタムポリシーの作成方法については、を参照してください"]。



== 2021 年 12 月 16 日



=== ダークサイトのデータをスキャンするデータ検出機能

Cloud Manager （コネクタ）と Cloud Data Sense は、インターネットにアクセスできないオンプレミスサイトにも導入できます。セキュアなサイトで Cloud Manager を使用して、オンプレミスの ONTAP クラスタを管理し、クラスタ間でデータをレプリケートし、クラウドデータセンスを使用してそれらのクラスタからデータをスキャンできるようになります。

link:task-deploy-compliance-dark-site.html["インターネットにアクセスできないサイトに Cloud Data Sense を導入する方法をご確認ください"^]。



== 2021 年 11 月 28 日



=== データセンスを使用すると、 ONTAP システムからボリュームをクローニングできます

ONTAP のクローニングには Data Sense を使用できますが、新しいクローンボリューム内のソースボリュームから選択したファイルのみを含めることができます。これは、データを移行して特定のファイルを除外する場合や、テスト用にボリュームのコピーを作成する場合に役立ちます。

link:task-managing-highlights.html#cloning-volume-data-to-a-new-volume["ボリュームをクローニングする方法を参照してください"]。



=== Cloud Manager の GCP Marketplace サブスクリプションでは、 Cloud Data Sense がサポートされるようになりました

。 https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project&rif_reserved["Cloud Manager の GCP Marketplace サブスクリプション"^] クラウドデータセンスのサポートが追加されました。従量課金制（ PAYGO ）サブスクリプションを使用して、ネットアップのライセンスを使用するだけでなく、 Google Cloud ストレージに導入された Cloud Volumes ONTAP システムからデータをスキャンできるようになりました。



=== 長時間実行されているコンプライアンスアクションのステータスを表示する機能

たとえば、 50 個のファイルを削除するなど、多くのファイルで [ 調査結果 ] ペインからアクションを実行する場合、プロセスには時間がかかることがあります。これらの非同期アクションのステータスを監視できるようになり、すべてのファイルにいつ適用されたかを確認できます。

link:task-managing-highlights.html#viewing-the-status-of-your-compliance-actions["継続的なコンプライアンスアクションのステータスを表示する方法をご確認ください"]。



=== 追加の 2 種類の個人データは、データセンスで識別できます

データセンスは、個人データの種類「 British Passport 」と「 National Health Service （ NHS ） Number 」をファイルで見つけることができるようになりました。 link:reference-private-data-categories.html#types-of-personal-data["スキャンで検出されたすべての個人データタイプのリストを表示します"]。



=== 新しいフィルタ（ New Filter ）：特定のタイプの作業環境に属するファイルを表示します

[ データ調査 ] ページでデータをフィルタリングするときに、 [ 作業環境タイプ ] の新しいフィルタが追加されました。これにより、 Cloud Volumes ONTAP システムの結果、 ONTAP システムの FSX 、オンプレミスの ONTAP システムなどをフィルタリングできます。



== 2021 年 11 月 7 日



=== 作業環境内の個々のボリュームをマッピングまたは分類できるようになりました

これまでは、すべてのボリュームをマッピングするか、各作業環境内のすべてのボリュームをマッピングして分類できました。これで、個々のボリュームをマッピングまたは分類することができます。このオプションは、 Cloud Volumes ONTAP ボリューム、 ANF ボリューム、オンプレミス ONTAP ボリューム、 ONTAP ボリュームで FSX を使用できます。



=== データセンスでは、データソースからデスティネーションの NFS 共有にファイルをコピーできます

データがスキャンしているすべてのソースファイルをデスティネーション NFS 共有にコピーできます。これは、特定のデータのコピーを作成して別の NFS の場所に移動する場合に便利です。 link:task-managing-highlights.html#copying-source-files-to-an-nfs-share["詳細はこちら。"]。



=== ONTAP ファイルシステムの FSX 上のデータ保護ボリュームをスキャンする機能

FSX で ONTAP ファイルシステムのデータ保護ボリュームをスキャンできるようになりました。 link:task-scanning-fsx.html#scanning-data-protection-volumes["詳細はこちら。"]。



=== 新しいフィルタ：データ検出によって最初にファイルが検出されたときに、日付範囲別にファイルを表示します

[ 調査 ] ページの [ 検出時刻 ] という新しいフィルタを使用すると、データ検出によって最初にファイルが検出されたときに、日付範囲別にファイルを表示できます。また、 [ ファイルの詳細 ] ページや、ファイルの CSV 形式で出力したレポートにも、 [ 検出時刻 ] が追加されています。



=== SOC 2 Type 2 認定

独立認定会計士事務所およびサービス監査役は、クラウドデータの意味を調査し、該当する信託業務基準に基づいて SOC 2 Type 2 の報告書を達成したことを確認しました。

https://www.netapp.com/company/trust-center/compliance/soc-2/["ネットアップの SOC 2 レポートをご覧ください"^]。



== 2021 年 10 月 4 日



=== ネットアップが提供する BYOL ライセンスがサポートされています

クラウドプロバイダマーケットプレイスでデータセンスのライセンスを取得することに加え、ネットアップから Bring Your Own License （ BYOL ；お客様所有のライセンスを使用）を購入できるようになりました。これは、 Cloud Manager アカウント内のすべての作業環境とデータソースで使用できます。

link:task-licensing-datasense.html#use-a-cloud-data-sense-byol-license["新しい Cloud Data Sense BYOL ライセンスの詳細については、こちらをご覧ください"]。



=== Google Cloud Platform のサポート

Cloud Data Sense は、 GCP に導入されている Cloud Volumes ONTAP システムからデータをスキャンできるようになりました。データセンスは GCP に導入する必要があり、コネクタは GCP またはオンプレミスに導入する必要があります。Connector に関連付けられた GCP サービスアカウントには、 Cloud Data Sense を GCP に導入するための最新の権限が必要です。



=== FSX 上の CIFS ボリュームをスキャンして ONTAP ファイルシステムを検出する機能

データセンスは、 FSX から ONTAP システムの CIFS ボリュームをスキャンできるようになりました。 link:task-scanning-fsx.html["Amazon FSX で ONTAP ボリュームをスキャンする方法を参照してください"]。



== 2021 年 9 月 2 日



=== ONTAP ファイルシステムの FSX 上の NFS ボリュームをスキャンする機能

Amazon FSX for ONTAP システムで NFS ボリューム上のデータのスキャンがサポートされるようになりました。 link:task-scanning-fsx.html["FSX for ONTAP システムのスキャンを設定する方法を参照してください"]。



=== データセンスの「ステータス」エントリが「タグ」エントリに変更されました

データセンスを使用してファイルに「ステータス」情報を追加する機能により、用語が「タグ」に変更されました。これらはファイルレベルのタグであり、ボリューム、 EC2 インスタンス、仮想マシンなどに適用できるリソースレベルのタグと混同しないでください link:task-org-private-data.html#applying-tags-to-manage-your-scanned-files["ファイルレベルのタグの詳細については、こちらをご覧ください"]。



== 2021 年 8 月 1 日



=== 複数のファイルのファイル設定を一度に管理できます

以前のバージョンの Cloud Data Sense では、一度に 1 つのファイルに対して次のアクションを実行できました。ステータスタグの追加、ユーザの割り当て、および AIP ラベルの追加。[ データ調査 ] ページから複数のファイルを選択し、これらの各アクションを複数のファイルに対して実行できるようになりました。



=== ガバナンスダッシュボードには、データが作成された日時または最後にアクセスされた日時に基づいてデータが表示されます

データの経過時間グラフをガバナンスダッシュボードで表示する場合、最後に変更された日時に基づいてデータを表示するだけでなく、作成日時または最終アクセス日時（読み取り時）に基づいてデータを表示できるようになりました。この情報は、データマッピングレポートにも記載されています。



=== 大規模な構成をスキャンする際に、複数のホストを使用して処理能力を高めることができます

オンプレミスにデータセンスを導入する場合、ペタバイト規模のデータを含む構成をスキャンする予定のときに、オンプレミスの他のホストにスキャンソフトウェアをインストールできるようになりました。これらの追加スキャナノードは、非常に大規模な構成をスキャンする際に処理能力を向上させます。

方法を参照してください link:task-deploy-compliance-onprem.html#multi-host-installation-for-large-configurations["Data Sense ソフトウェアを複数のホストに導入する"]。



== 2021 年 7 月 7 日



=== データセンスでは、データソースからデスティネーションの NFS 共有にファイルを移動できます

新しい機能を使用すると、を実行できます link:task-managing-highlights.html#moving-source-files-to-an-nfs-share["データがスキャンしているソースファイルをすべての NFS 共有に移動します"]。これにより、機密ファイルやセキュリティ関連ファイルを特別な領域に移動して、より詳細な分析を行うことができます。



=== 完全な分類スキャンを実行する代わりに、データをすばやく分類する機能

完全な分類スキャンを実行する代わりに、データをカテゴリにすばやくマッピングするように選択できるようになりました。これにより、を実行できます link:task-generating-compliance-reports.html#data-mapping-report["データマッピングレポートを表示します"] ガバナンスダッシュボードでは、完全なスキャンを実行する必要がない特定のデータソースがある場合に、データの概要を確認できます。



=== Cloud Manager ユーザにファイルを割り当てる機能

できるようになりました。 link:task-org-private-data.html#assigning-users-to-manage-certain-files["ファイルを特定の Cloud Manager ユーザに割り当てます"] そのため、ファイルに対して行う必要があるフォローアップアクションを担当することができます。この機能を既存のフィーチャーとともに使用して、カスタムタグをファイルに追加できます。

[ 調査 ] ページの新しいフィルタを使用すると、 [ 割り当て先 ] フィールドに同じユーザーを持つすべてのファイルを簡単に表示することもできます。



=== より小さいクラウドデータセンスインスタンスを使用できます

スキャン要件が小さいユーザの中には、より小さいクラウドデータセンスインスタンスを使用できるようにする必要のあるユーザもいます。できるようになりました。これらの小規模なインスタンスを使用する場合は、いくつかの制限事項があります link:concept-cloud-compliance.html#using-a-smaller-instance-type["これらの制限事項を最初に確認してください"]。



=== 低速スキャンを実行する機能

データスキャンは、ストレージシステムとデータにほとんど影響を与えません。ただし、影響が非常に小さい場合でも、「低速」スキャンを実行するように Data Sense を設定できます。 link:task-managing-compliance.html#reducing-the-data-sense-scan-speed["方法を参照してください"]。



=== データセンスは、ファイルが最後にアクセスされた時刻を追跡します

[ ファイルの詳細 ] ページとレポートに [ 最終アクセス日時 ] の値が追加され、 CSV 形式で出力されます。これにより、ユーザーがファイルに最後にアクセスしたときを確認できます。



== 2021 年 6 月 7 日



=== Cloud Compliance の名前が「 Cloud Data Sense 」に変更されました。

Cloud Compliance の名称は、今回のリリースから「 Cloud Data Sense * 」に変更されました。製品に含まれている新しいガバナンスやその他の機能を活用することで、コンプライアンスの名称は機能の完全なセットを促進するものではありませんでした。



=== 新しい「フルデータマッピング」レポートは、 Governance Dashboard から入手できます

ガバナンスダッシュボードから新しい _ フルデータマッピング _ レポートを使用して、企業のデータソースに保存されているデータの概要を表示し、移行、バックアップ、セキュリティ、コンプライアンスの各プロセスの決定を支援します。

このレポートには、すべての作業環境とデータソースをまとめた概要ページが表示され、それぞれの作業環境の内訳が表示されます。 link:task-generating-compliance-reports.html#generating-the-data-mapping-report["ここに移動します"] 詳細：



=== 重複しているすべてのファイルを表示するには、 ［ 調査 ］ ページの新しいフィルタを使用します

Data Investigation ページの新しいフィルタを使用すると、ストレージシステム間で複製されているすべてのファイルのリストを表示できます。これは、ストレージスペースを節約できる領域を特定したり、特定の権限または機密情報を持つファイルを特定したりするのに役立ちます。これらのファイルには、ストレージ間で複製しない領域が含まれます。 link:task-controlling-private-data.html#viewing-all-duplicated-files["すべての重複ファイルを表示する方法を参照してください"]。



=== データセンスは、組織のファイルにカスタムタグを追加できます

データセンスがスキャンしているファイルにカスタムタグを追加できます。AIP ラベルが追加されるのと同じ方法で、タグがファイルに追加されません。タグは Cloud Manager ユーザに表示されるばかりなので、ファイルを削除する必要があるかどうか、何らかの理由で確認する必要があるかどうかを指定できます。 link:task-org-private-data.html#applying-tags-to-manage-your-scanned-files["ファイルにタグを適用して表示する方法を参照してください"]。

[ 調査 ] ページの新しいフィルタを使用すると、タグが割り当てられているすべてのファイルを簡単に表示できます。



=== .dcm および .dicom ファイルのスキャン機能

クラウドデータセンスは、 .dcm と .dicom の 2 種類の追加ファイルで個人識別情報（ PII ）をスキャンできます。



=== データセンスは、ファイルの追加属性を追跡するようになりました

CSV 形式で出力するレポートには、 [ ファイルサイズ ] 、 [ 作成日 ] 、および [ 最終変更日 ] の値が追加されています。作成日は、調査ページの検索結果を絞り込むために使用できる新しいフィルタでもあります。
